window.COMMENT_BANK = [
  // 早上 morning
  { "id": "c0001", "text": "今天早上来练，庭教练帮我看了下深蹲姿势，纠正了几个细节，完全不强行推课，就是很自然地给建议，这种感觉很舒服。", "tags": ["private_training"], "timeSlot": "morning" },
  { "id": "c0002", "text": "早上人少，教练有空就过来看一眼，主动帮我调整动作，不会给你任何压力，练完感觉比自己摸索快多了。", "tags": ["private_training", "training_effect"], "timeSlot": "morning" },
  { "id": "c0003", "text": "早上来试了私教体验课，庭教练很专业，一点一点细心教，针对我的情况安排训练，完全不是走过场的那种。", "tags": ["private_training"], "timeSlot": "morning" },
  { "id": "c0004", "text": "早上来练器械，哑铃从小重量到大重量都有，固定器械也很全，想练什么部位基本都能安排上，老手新手都够用。", "tags": ["equipment"], "timeSlot": "morning" },
  { "id": "c0005", "text": "晨练这趟很顺，器械摆放清楚，设备都是新的，发力感很好，比我之前去的那家强多了。", "tags": ["equipment", "training_effect"], "timeSlot": "morning" },
  { "id": "c0006", "text": "早起打卡，器械区宽敞，不用等设备，地面干净没汗渍，整个人练起来很舒畅。", "tags": ["equipment", "environment"], "timeSlot": "morning" },
  { "id": "c0007", "text": "早上六点多来，灯光亮堂，空调舒适，音乐节奏刚好，不会太吵也不会太安静，整个环境让人很想动起来。", "tags": ["environment", "atmosphere"], "timeSlot": "morning" },
  { "id": "c0008", "text": "晨练环境真的不错，每个角落都干净，地面没有脚印汗渍，氛围轻松不压抑，练完状态很好。", "tags": ["environment"], "timeSlot": "morning" },
  { "id": "c0009", "text": "早上来练，场地整洁，器械区和有氧区动线清楚，第一次来也不会找不着北，很顺手。", "tags": ["environment", "front_desk"], "timeSlot": "morning" },
  { "id": "c0010", "text": "练完洗澡，水温很稳定，淋浴间干净没异味，更衣区够用，整个流程很顺，练完洗完直接去上班刚刚好。", "tags": ["shower"], "timeSlot": "morning" },
  { "id": "c0011", "text": "早练完冲个澡再出门，淋浴设施干净整洁，这个细节做得很好，对上班族来说太重要了。", "tags": ["shower", "front_desk"], "timeSlot": "morning" },
  { "id": "c0012", "text": "早上来练了一小时，力量有氧都安排了，庭教练顺手帮我看了下动作，感觉比自己瞎练进步快。", "tags": ["training_effect", "private_training"], "timeSlot": "morning" },
  { "id": "c0013", "text": "坚持早训一个月了，感觉体能明显好了，这边的环境和氛围让人很容易坚持下来。", "tags": ["training_effect", "atmosphere"], "timeSlot": "morning" },
  { "id": "c0014", "text": "第一次来，扫脸进场很方便，前台热情带我转了一圈，没有强行推销，很自在，当天就入手月卡了。", "tags": ["front_desk"], "timeSlot": "morning" },
  { "id": "c0015", "text": "朋友介绍过来的，进场扫脸就行，工作人员很亲切，有问必答，整体体验比想象中好很多。", "tags": ["front_desk"], "timeSlot": "morning" },
  { "id": "c0016", "text": "早上的氛围很纯粹，来的人都在专心练，没人喧哗，适合想专心训练的人，这种感觉很难得。", "tags": ["atmosphere"], "timeSlot": "morning" },
  { "id": "c0017", "text": "朋友介绍来的，本来不信这么便宜环境还能这么好，来了才知道是真的。停车免费，扫脸进场，教练专业不推课，性价比真的高。", "tags": ["front_desk", "equipment", "private_training"], "timeSlot": "morning" },
  { "id": "c0018", "text": "练了半年了，从完全不会到现在有自己的训练计划，庭教练功不可没，专业且真心帮你进步。", "tags": ["private_training", "training_effect"], "timeSlot": "morning" },
  { "id": "c0019", "text": "每个角落都很干净，设备非常全，价格不贵，教练认真负责，就在体育中心里面，值得推荐！", "tags": ["environment", "equipment", "private_training"], "timeSlot": "morning" },
  { "id": "c0020", "text": "健身房停车场免费，对于开车来的人来说真的很加分，加上24小时开放，选它没什么理由不选。", "tags": ["front_desk"], "timeSlot": "morning" },
  { "id": "c0021", "text": "地面真的干净，练完地上没有汗渍，更衣室收拾得整齐，这些细节说明管理很用心。", "tags": ["environment", "shower"], "timeSlot": "morning" },
  { "id": "c0022", "text": "训练效果这段时间感觉很明显，主要是动作做对了，教练这边帮了很大忙，比自己摸索强太多。", "tags": ["training_effect", "private_training"], "timeSlot": "morning" },

  // 午间 noon
  { "id": "c0023", "text": "午休来练了一节私教，庭教练根据我的情况安排动作，讲解很细致，练完感觉很扎实，不是那种硬撑出来的累。", "tags": ["private_training", "training_effect"], "timeSlot": "noon" },
  { "id": "c0024", "text": "中午来体验了一下私教课，教练专业且有耐心，免费帮我纠正了好几个动作错误，直接避免了受伤风险。", "tags": ["private_training"], "timeSlot": "noon" },
  { "id": "c0025", "text": "午饭后来练，人不算多，器械基本都能用上，设备新，状态好，练了45分钟很舒服。", "tags": ["equipment"], "timeSlot": "noon" },
  { "id": "c0026", "text": "中午来打卡，力量区器械很齐全，哑铃、杠铃、固定器械都有，新手进来也不会不知道从哪练起。", "tags": ["equipment"], "timeSlot": "noon" },
  { "id": "c0027", "text": "中午来练，场地干净，空调温度舒适，不会练到一半热到崩溃，整体环境很加分。", "tags": ["environment"], "timeSlot": "noon" },
  { "id": "c0028", "text": "利用午休时间来练，环境比我预期的好很多，整洁宽敞，灯光也舒服，不会有压抑感。", "tags": ["environment", "atmosphere"], "timeSlot": "noon" },
  { "id": "c0029", "text": "坚持来了两个月，每次中午练完下午状态反而更好，整体精力提升了不少，很推荐上班族来这里。", "tags": ["training_effect"], "timeSlot": "noon" },
  { "id": "c0030", "text": "午休练了一小时，教练帮我调整了动作细节，感觉肌肉真正被练到了，不是瞎出汗的那种。", "tags": ["training_effect", "private_training"], "timeSlot": "noon" },
  { "id": "c0031", "text": "中午第一次来，工作人员很热情地介绍了一遍设施，没有推销压力，扫脸注册完直接开练，很方便。", "tags": ["front_desk"], "timeSlot": "noon" },
  { "id": "c0032", "text": "中午来练的时候人不多，氛围安静专注，大家都在认真训练，很适合利用碎片时间好好练一场。", "tags": ["atmosphere"], "timeSlot": "noon" },
  { "id": "c0033", "text": "中午练完冲个澡再吃饭，淋浴间干净，水温稳定，换上干净衣服去吃饭感觉整个人都清爽了。", "tags": ["shower"], "timeSlot": "noon" },
  { "id": "c0034", "text": "教练从来不主动推课，但你问他问题随时都给你耐心解答，这种分寸感让人很舒服。", "tags": ["private_training"], "timeSlot": "noon" },
  { "id": "c0035", "text": "设施新、环境棒、教练好、氛围赞，附近健身首选，性价比高，闭眼入。", "tags": ["equipment", "environment", "private_training", "atmosphere"], "timeSlot": "noon" },
  { "id": "c0036", "text": "以前觉得健身太贵，来这边发现价格真的不贵，环境比很多贵的地方还好，早来早享受。", "tags": ["environment", "atmosphere"], "timeSlot": "noon" },

  // 下午 afternoon
  { "id": "c0037", "text": "下午来练，庭教练刚好有空，过来帮我看了看训练计划，给了一些调整建议，专业程度真的高，而且完全是免费的。", "tags": ["private_training"], "timeSlot": "afternoon" },
  { "id": "c0038", "text": "下午私教课结束，教练耐心程度超出预期，针对我的目标来安排，减脂效果这段时间明显感受到了。", "tags": ["private_training", "training_effect"], "timeSlot": "afternoon" },
  { "id": "c0039", "text": "下午来练，器械区设备齐全，想做的动作都能找到对应器械，设备质量也不错，发力感很好。", "tags": ["equipment"], "timeSlot": "afternoon" },
  { "id": "c0040", "text": "下午人少，器械随便用，哑铃架满的，各重量段都有，练胸练背练腿都能安排，很爽。", "tags": ["equipment"], "timeSlot": "afternoon" },
  { "id": "c0041", "text": "下午来练，阳光透进来，整个场馆很明亮，氛围轻松，练起来心情很好。", "tags": ["environment", "atmosphere"], "timeSlot": "afternoon" },
  { "id": "c0042", "text": "下午过来打卡，整体环境维护得很好，地面干净，器械摆放整齐，工作人员在场，安心。", "tags": ["environment", "front_desk"], "timeSlot": "afternoon" },
  { "id": "c0043", "text": "下午来练的人氛围很好，有在做力量的有在跑步的，大家都很专注，不会有那种互相比较的压力感。", "tags": ["atmosphere"], "timeSlot": "afternoon" },
  { "id": "c0044", "text": "下午的健身房很舒服，不会太吵，音乐节奏适中，在这里练起来很放松，不自觉就多练了半小时。", "tags": ["atmosphere", "environment"], "timeSlot": "afternoon" },
  { "id": "c0045", "text": "下午练完，淋浴间干净整洁，水压够，水温稳，洗完很舒服，整体配套设施挺完善的。", "tags": ["shower"], "timeSlot": "afternoon" },
  { "id": "c0046", "text": "下午来练了背和手臂，按教练之前教我的方法来，感觉发力点对了很多，练完酸胀感很到位。", "tags": ["training_effect", "private_training"], "timeSlot": "afternoon" },
  { "id": "c0047", "text": "坚持练了一段时间，下午来练效率很高，这边器械配置合理，基本不用等，一小时练完很充实。", "tags": ["training_effect", "equipment"], "timeSlot": "afternoon" },
  { "id": "c0048", "text": "下午带朋友来参观，工作人员很热情介绍，没有任何推销压力，朋友当场就决定办卡了。", "tags": ["front_desk"], "timeSlot": "afternoon" },
  { "id": "c0049", "text": "快夏天了来报了个健身房，环境非常好，每个角落都干净，设备也非常全，价格不贵，教练专业认真负责，姐妹们可以一起来打卡！", "tags": ["environment", "equipment", "private_training"], "timeSlot": "afternoon" },
  { "id": "c0050", "text": "在体育中心旁边，交通方便停车也好停，进来发现配置超出预期，器械新，环境干净，教练友好，真的值得推荐。", "tags": ["equipment", "environment", "front_desk"], "timeSlot": "afternoon" },
  { "id": "c0051", "text": "女生来练完全不会不自在，氛围很好，大家都在专心练自己的，教练也很尊重人，推荐女生来。", "tags": ["atmosphere", "private_training"], "timeSlot": "afternoon" },
  { "id": "c0052", "text": "第一次来不会用器械，教练主动过来帮我，讲了基础动作，没有趁机推课，这种服务态度真的加分。", "tags": ["private_training", "front_desk"], "timeSlot": "afternoon" },
  { "id": "c0053", "text": "来了以后才发现这边器械比想象中全多了，力量区有氧区都很齐，适合各种训练目标的人来练。", "tags": ["equipment"], "timeSlot": "afternoon" },
  { "id": "c0054", "text": "庭教练帮我纠了姿势，之前膝盖总是不舒服，现在深蹲姿势对了，膝盖好多了，专业程度真的高。", "tags": ["private_training", "training_effect"], "timeSlot": "afternoon" },
  { "id": "c0055", "text": "体育中心这边交通不错，开车停车都方便，进馆扫脸，工作人员热情，整体体验很顺。", "tags": ["front_desk"], "timeSlot": "afternoon" },
  { "id": "c0056", "text": "每次来练完冲个澡，淋浴间干净卫生，整体配套完善，这边真的适合日常健身打卡。", "tags": ["shower", "environment"], "timeSlot": "afternoon" },

  // 晚高峰 evening
  { "id": "c0057", "text": "下班来练，庭教练还在，看到我在练深蹲主动过来帮我看了下姿势，这种不强迫但真心帮你的感觉，真的很好。", "tags": ["private_training"], "timeSlot": "evening" },
  { "id": "c0058", "text": "晚上来练私教，庭教练很认真，针对我的薄弱点专门设计了动作，练完很扎实，不是那种走流程的课。", "tags": ["private_training", "training_effect"], "timeSlot": "evening" },
  { "id": "c0059", "text": "下班后来上私教，教练专业有耐心，每个动作都讲得很详细，不懂随时问都行，从来不会让你有被敷衍的感觉。", "tags": ["private_training"], "timeSlot": "evening" },
  { "id": "c0060", "text": "下班高峰期来，器械等待时间还好，设备够多，基本能安排到想练的部位，配置真的挺全的。", "tags": ["equipment"], "timeSlot": "evening" },
  { "id": "c0061", "text": "晚上来练，力量器械、有氧器械都很齐全，设备新，质量好，跟大健身房的配置差不了多少，价格却亲民很多。", "tags": ["equipment", "atmosphere"], "timeSlot": "evening" },
  { "id": "c0062", "text": "下班来练，灯光和音乐刚刚好，不会太high也不会太沉闷，换个环境动一动，整个人压力小了很多。", "tags": ["environment", "atmosphere"], "timeSlot": "evening" },
  { "id": "c0063", "text": "晚上来练，场馆干净整洁，通风好，练完不会感觉闷，淋浴间也干净，配套很完善。", "tags": ["environment", "shower"], "timeSlot": "evening" },
  { "id": "c0064", "text": "下班来练的氛围很好，大家都是来认真练的，不会有奇怪的眼神，新手来也不会不自在。", "tags": ["atmosphere"], "timeSlot": "evening" },
  { "id": "c0065", "text": "晚上的健身房氛围很纯粹，没有那种互相展示的浮躁气，就是专心练，很适合想认真训练的人。", "tags": ["atmosphere"], "timeSlot": "evening" },
  { "id": "c0066", "text": "下班来打卡，场馆在体育中心里面，停车免费，进门扫脸就行，整个流程很顺，不麻烦。", "tags": ["front_desk"], "timeSlot": "evening" },
  { "id": "c0067", "text": "晚上练完洗澡再回家，淋浴间干净，水温热乎，洗完整个人很舒服，不用担心卫生问题。", "tags": ["shower"], "timeSlot": "evening" },
  { "id": "c0068", "text": "下班练完冲个澡，淋浴设施干净，更衣柜够用，整体配套做得很到位，对上班族很友好。", "tags": ["shower", "front_desk"], "timeSlot": "evening" },
  { "id": "c0069", "text": "坚持来了三个月，下班练完再回家这个习惯养成了，体能好了很多，整体状态比以前好很多。", "tags": ["training_effect"], "timeSlot": "evening" },
  { "id": "c0070", "text": "晚上来练了腿，教练之前帮我调整过姿势，今天感觉发力点对了，酸胀感很到位，练完很满足。", "tags": ["training_effect", "private_training"], "timeSlot": "evening" },
  { "id": "c0071", "text": "下班来练，一小时力量加半小时有氧，效率很高，这边器械配置合理，基本不用等，练完很充实。", "tags": ["training_effect", "equipment"], "timeSlot": "evening" },
  { "id": "c0072", "text": "下班过来，工作人员很热情，有什么问题都耐心解答，不会强推课程，氛围很舒适。", "tags": ["front_desk"], "timeSlot": "evening" },
  { "id": "c0073", "text": "上班族推荐，24小时随时来练，停车免费，扫脸进场，价格亲民，教练不强行推课，练完洗澡再回家，完美。", "tags": ["front_desk", "shower", "private_training"], "timeSlot": "evening" },
  { "id": "c0074", "text": "老手够用，新手好上手，卫生做得到位，地面无汗渍，淋浴间干净，教练专业不强行推课，训练氛围纯粹，性价比超高！", "tags": ["equipment", "shower", "private_training", "atmosphere"], "timeSlot": "evening" },
  { "id": "c0075", "text": "每次锻炼都能得到教练的专业指导，让我对健身更有信心，健身房设施齐全，音乐灯光都恰到好处，在这里锻炼真的是享受。", "tags": ["private_training", "equipment", "atmosphere", "training_effect"], "timeSlot": "evening" },
  { "id": "c0076", "text": "力量训练加有氧，每次来都练得很扎实，这边的环境和教练都很好，已经养成了规律运动的习惯。", "tags": ["training_effect", "environment", "private_training"], "timeSlot": "evening" },
  { "id": "c0077", "text": "音乐选得不错，节奏带感但不会吵到无法专注，灯光也舒服，在这里练起来整体体验很好。", "tags": ["atmosphere", "environment"], "timeSlot": "evening" },
  { "id": "c0078", "text": "练了两个月，之前老觉得坚持不下来，在这里反而越练越有劲，氛围好是主要原因。", "tags": ["atmosphere", "training_effect"], "timeSlot": "evening" },
  { "id": "c0079", "text": "女生专属建议：这边氛围轻松不压抑，没有被人打量的感觉，教练也很专业不乱来，放心练。", "tags": ["atmosphere", "private_training"], "timeSlot": "evening" },
  { "id": "c0080", "text": "第一次晚上来，担心找不到地方，工作人员主动带我参观，介绍得很清楚，当场就办了月卡。", "tags": ["front_desk"], "timeSlot": "evening" },

  // 夜训 night
  { "id": "c0081", "text": "夜班族专属时间来练，器械全是自己的，不用等，不用抢，安安静静把今天的训练完成，很爽。", "tags": ["equipment", "atmosphere"], "timeSlot": "night" },
  { "id": "c0082", "text": "凌晨来练，器械全部可以用，一个人整个力量区随便用，这种感觉太爽了，24小时真的很值。", "tags": ["equipment"], "timeSlot": "night" },
  { "id": "c0083", "text": "深夜来练，场馆干净整洁，灯光正常，不会因为是夜间就偷懒，整体维护很用心。", "tags": ["environment"], "timeSlot": "night" },
  { "id": "c0084", "text": "夜训的环境很安静，就自己一两个人，音乐放着，练起来特别专注，效率超高。", "tags": ["environment", "atmosphere"], "timeSlot": "night" },
  { "id": "c0085", "text": "深夜来练的氛围很特别，安静但不孤独，就是专心干自己的事，24小时开放对夜猫子来说真的太重要了。", "tags": ["atmosphere"], "timeSlot": "night" },
  { "id": "c0086", "text": "熬夜族福利，深夜练完睡得更好，24小时扫脸进场，随时来随时练，自由度很高。", "tags": ["atmosphere", "front_desk"], "timeSlot": "night" },
  { "id": "c0087", "text": "夜训氛围很纯粹，来的人都是认真练的，大家互不打扰，专注度比白天高，很享受这个状态。", "tags": ["atmosphere"], "timeSlot": "night" },
  { "id": "c0088", "text": "夜训完冲个澡，淋浴间干净，凌晨来也一样整洁，不会因为是深夜就变差，管理很到位。", "tags": ["shower"], "timeSlot": "night" },
  { "id": "c0089", "text": "坚持夜训一段时间，整体体态改善了很多，教练给的训练方向很对，不是瞎练，有目标有进步。", "tags": ["training_effect", "private_training"], "timeSlot": "night" },
  { "id": "c0090", "text": "深夜练了背和二头，器械随便用，专注度很高，练完感觉很好，比白天人多的时候练得更扎实。", "tags": ["training_effect", "equipment"], "timeSlot": "night" },
  { "id": "c0091", "text": "凌晨来练，扫脸进场很方便，安全感很好，场馆管理到位，不会有任何顾虑，放心练就行。", "tags": ["front_desk"], "timeSlot": "night" },
  { "id": "c0092", "text": "健身房在体育中心里，停车不要钱，扫脸进场，24小时开放，对我们打工人来说真的太方便了，价格也很亲民。", "tags": ["front_desk"], "timeSlot": "night" },
  { "id": "c0093", "text": "夜班族必推，凌晨来练完睡一觉，整个人状态好很多，24小时这个配置真的是选这里最大的理由。", "tags": ["front_desk", "training_effect"], "timeSlot": "night" },
  { "id": "c0094", "text": "深夜来练完练完，整个力量区随便用，这种自由感是在大健身房感受不到的，24小时超值。", "tags": ["equipment", "atmosphere"], "timeSlot": "night" },
  { "id": "c0095", "text": "庭教练白天帮我排好了训练计划，夜里照着练，完全不迷茫，效率比以前高多了。", "tags": ["private_training", "training_effect"], "timeSlot": "night" },
  { "id": "c0096", "text": "扫脸进场安全感很强，不用带卡不怕忘，24小时随时能来，真的很适合生活不规律的人。", "tags": ["front_desk"], "timeSlot": "night" },
  { "id": "c0097", "text": "第一次被朋友带来，现在已经变成这里的常客了，性价比这么高的健身房真的不多，附近首选。", "tags": ["atmosphere", "front_desk"], "timeSlot": "night" }
];
